---
# file: roles/filebeat/tasks/main.yml
- name: install java and filebeat
  yum: name="{{ item }}" state=present
  loop:
     - java-openjdk
     - filebeat

- name: drop in filebeat yml template
  template: src=filebeat.yml.j2 dest=/etc/filebeat/filebeat.yml

- name: copy logstash ssl
  copy: src=/tmp/logstash-forwarder.crt dest=/etc/pki/tls/certs/logstash-forwarder.crt 

- name: enable filebeat service
  systemd: state=restarted name=filebeat enabled=yes
