---
# file: roles/logstash/tasks/main.yml
- name: install java and logstash
  yum: name={{ item }} state=present
  with_items:
     - java-openjdk
     - logstash

- name: ssl for logbeat
  command: openssl req -subj '/CN={{ ansible_nodename }}/' -x509 -days 3650 -batch -nodes -newkey rsa:2048 -keyout /etc/pki/tls/private/logstash-forwarder.key -out /etc/pki/tls/certs/logstash-forwarder.crt

- name: logstash logbeat input
  copy: src=02-beats-input.conf dest=/etc/logstash/conf.d/02-beats-input.conf

- name: logstash syslog transform
  copy: src=10-syslog-filter.conf dest=/etc/logstash/conf.d/10-syslog-filter.conf

- name: logstash elasticsearch output
  template: src=30-elasticsearch-output.conf.j2 dest=/etc/logstash/conf.d/30-elasticsearch-output.conf

- name: check logstash configs
  command: service logstash configtest

- name: restart logstash service
  command: systemctl restart logstash

- name: config logstash to start at boot
  command: chkconfig logstash on   


