---
# file: roles/nginx/tasks/main.yml
- name: install nginx
  yum: name={{ item }} state=present
  with_items:
    - nginx
    - httpd-tools
    - python-passlib

- name: create kibana admin user
  htpasswd: path=/etc/nginx/htpasswd.users name=kibadmin password={{ kibadminpw }}

- name: copy nginx cfg file
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf 

- name: copy kibana cfg file
  template: src=nginx_kibana_conf.j2 dest=/etc/nginx/conf.d/kibana.conf

- name: enable nginx service
  command: systemctl enable nginx.service
 
- name: start nginx
  command: systemctl start nginx.service

