---
# file: roles/kibana/tasks/main.yml
- name: install java and kibana
  yum: name={{ item }} state=present
  with_items:
     - java-openjdk
     - kibana


# edit /opt/kibana/config/kibana.yml to restrict access to localhost only
# systemctl start kibana
# chkconfig kibana on
