---
# file: roles/nginx/tasks/main.yml
- name: install nginx
  yum: name="{{ item }}" state=present
  loop:
    - nginx
    - httpd-tools
    - python-passlib

- name: import kibana admin password from vault
  include: kib_admin.yml

- name: create kibana admin user
  htpasswd: path=/etc/nginx/htpasswd.users name=kibadmin password={{ kibadminpw }}

- name: copy nginx cfg file
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf 
  register: nginx

- name: copy kibana cfg file
  template: src=nginx_kibana_conf.j2 dest=/etc/nginx/conf.d/kibana.conf

- name: logstash input firewall rules
  firewalld: rich_rule='rule family="ipv4" source address="192.168.0.0/16" port protocol="tcp" port="{{ item }}" accept' permanent=true immediate=true state=enabled
  loop:
    - 80

- name: enable nginx service
  systemd: name=nginx state=restarted enabled=yes
  when: nginx.changed
