---
# file: roles/kibana/tasks/main.yml
- name: install java and kibana
  yum: name="{{ item }}" state=present
  loop:
     - java-openjdk
     - kibana
     - unzip

- name: start kibana
  systemd: name=kibana state=restarted enabled=yes
 
- name: copy filebeat dashboards
  copy: src=beats-dashboards-1.1.0.zip dest=/root/beats-dashboards-1.1.0.zip
 
- name: copy filebeat index template 
  copy: src=filebeat-index-template.json dest=/root/filebeat-index-template.json
