---
# file: roles/kibana/tasks/main.yml
- name: install java and kibana
  yum: name={{ item }} state=present
  with_items:
     - java-openjdk
     - kibana
     - unzip

- name: start kibana
  command: systemctl restart kibana
 
- name: config kibana to start at boot
  command: chkconfig kibana on

- name: copy filebeat dashboards
  copy: src=beats-dashboards-1.1.0.zip dest=/root/beats-dashboards-1.1.0.zip
 
- name: copy filebeat index template 
  copy: src=filebeat-index-template.json dest=/root/filebeat-index-template.json
